"""Ajout du champ is_read à Message

Revision ID: 1c07feb0f118
Revises: 22bd2e09d45b
Create Date: 2025-05-14 09:28:29.148138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c07feb0f118'
down_revision = '22bd2e09d45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.drop_column('lu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lu', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
