"""Ajout du champ file_size à Publication

Revision ID: 22bd2e09d45b
Revises: 
Create Date: 2025-05-14 06:35:02.837664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bd2e09d45b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
