"""Ajout du champ is_read à Message

Revision ID: cd9809459818
Revises: 1c07feb0f118
Create Date: 2025-05-14 09:35:05.092718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9809459818'
down_revision = '1c07feb0f118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lu', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('lu')

    # ### end Alembic commands ###
